### ISSUE TITLE
有个场景略微尴尬

### ISSUE THREAD

**Issue by eryajf** [wangmeijian/auto_clipboard#1]
很优秀的插件，但是如果我是在编辑界面，比如创建这个GitHub issue，我要复制A，然后选中B，再command+v覆盖掉，结果这个时候因为选中了B，粘贴板里的内容又是B，导致无法实现把A覆盖B的需求。

**Comment by wangmeijian** [comment]
第一个Issues，感谢您的反馈👨🏻‍💻！

普通的输入框，选中文本不会直接复制的，需要按住Ctrl键，我猜你说的编辑页面可能是用了DOM的contenteditable属性，这个确实没做判断，能说说在哪个网站能复现吗？在Githu的 Issue页面能正常使用

**Comment by eryajf** [comment]
的确我在issue这里测试没有问题，但是在GitHub中，直接编辑README的时候，就会有这个问题

**Comment by wangmeijian** [comment]
> 的确我在issue这里测试没有问题，但是在GitHub中，直接编辑README的时候，就会有这个问题

非常感谢，这边尽快处理

**Comment by wangmeijian** [comment]
已解决，更新到最新版本即可
