### ISSUE TITLE
有个比较麻烦的 BUG

### ISSUE THREAD

**Issue by AUENDXYZ** [wangmeijian/auto_clipboard#5]
用这个 auto_clipboard 的插件自动复制的 python 源代码， 粘贴到VSC中后，运行会出现：“SyntaxError: invalid non-printable character U+00A0” 的错误，我如果按其内容自己再重新打一遍内容，运行就不出错了。
请作者能想法修正此 BUG ，谢谢先！
要是有修改好的 crx 文件，麻烦也发给我一份重新安装 。
我的邮箱： auend@163.com

**Comment by wangmeijian** [comment]
非常感谢你的反馈，这边尽快处理

**Comment by wangmeijian** [comment]
@AUENDXYZ 在哪里复制的地址可以贴一下，试了几个没重现

**Comment by wangmeijian** [comment]
Chrome新版本已发布，Edge审核中
