### ISSUE TITLE
你好作者通用破解似乎适配有的问题

### ISSUE THREAD

**Issue by Master-Panda** [wangmeijian/auto_clipboard#7]
你好作者大大，https://www.zhihuishu.com/这个网址里面有的内容无法破解复制，我用其他的一个插件Talent划词翻译，却可以破解复制，反馈一下

**Comment by wangmeijian** [comment]
试了一下能正常复制，你是什么系统？你升级到最新的0.9.0版本试试呢

**Comment by Master-Panda** [comment]
> 试了一下能正常复制，你是什么系统？你升级到最新的0.9.0版本试试呢

作者你好我的是win系统，也是最新版的呢。一般的文字是可以复制的，不用插件的话也可以复制。但是一些特殊的页面比如作业考试，问答这些就不行了

**Comment by wangmeijian** [comment]
> > 试了一下能正常复制，你是什么系统？你升级到最新的0.9.0版本试试呢
> 
> 作者你好我的是win系统，也是最新版的呢。一般的文字是可以复制的，不用插件的话也可以复制。但是一些特殊的页面比如作业考试，问答这些就不行了

是有问题，下个版本适配~

**Comment by Master-Panda** [comment]
> > > 试了一下能正常复制，你是什么系统？你升级到最新的0.9.0版本试试呢
> > 
> > 
> > 作者你好我的是win系统，也是最新版的呢。一般的文字是可以复制的，不用插件的话也可以复制。但是一些特殊的页面比如作业考试，问答这些就不行了
> 
> 是有问题，下个版本适配~

辛苦大大

**Comment by wangmeijian** [comment]
chrome版本已发布，Edge版本审核中

**Comment by Master-Panda** [comment]
> chrome版本已发布，Edge版本审核中

好的，感谢作者大大
