### ISSUE TITLE
建议反馈:希望可以添加去除右键菜单的显示

### ISSUE THREAD

**Issue by veizei-K** [wangmeijian/auto_clipboard#9]
![image](https://github.com/wangmeijian/auto_clipboard/assets/129288685/98e903c0-baa3-485d-a63b-5fa54463dfdc)

**Comment by wangmeijian** [comment]
好的，安排

**Comment by wangmeijian** [comment]
![image](https://github.com/wangmeijian/auto_clipboard/assets/9384140/79c9c427-c8cd-458f-b618-4171836755ab)

已增加相关配置 @freedomspiritJohn
